conferences_and_journals = [
    "CVPR", "ICCV", "ECCV", "AAAI", "EMNLP", "IJCAI", "ACL", "NAACL",
    "ICML", "NeurIPS", "ICLR", "TPAMI", "IJCV", "JMLR", "TMLR",
    "WACV", "BMVC", "ACCV", "VISAPP", "Image and Vision Computing",
    "AISTATS", "COLT", "UAI", "KAIS", "AIJ",
    "TACL", "EACL", "COLING", "CL",
    "ICRA", "IROS", "RSS", "CoRL", "Autonomous Robots",
    "KDD", "ICDM", "SIGIR", "WWW", "WSDM", "CHI",
    "SIAM SDM", "MLJ"
]


reference_prefixes = [
    "There is a paper titled: ",
    "Citation: ",
    "The paper is presented: ",
    "The work is documented as follows: ",
    "In the literature, the following study is noted: ",
    "Reference: ",
    "The following research is referenced: ",
    "This study is detailed in the paper: ",
    "Consider the work titled: ",
    "This is articulated in: ",
    "The publication can be cited as: ",
    "The authors present their findings in: ",
    "The research is discussed in: ",
    "The following article elaborates on this: ",
    "The findings are captured in: ",
    "The investigation is reported in: ",
    "One example of this is: ",
    "In a related publication: ",
    "Details of this are found in: ",
    "The corresponding paper is titled: ",
    "The associated research is documented in: ",
    "This idea is explored in: ",
    "The topic is studied in: ",
    "The article reads: ",
    "According to the publication: ",
    "An example from the field is: ",
    "The authors of this paper highlight: ",
    "A detailed exploration is found in: ",
    "This research contribution is outlined in: ",
    "Their methodology is presented in: ",
    "The scientific community recognizes this in: ",
    "Insights are shared in: ",
    "This innovative approach is explained in: ",
    "The theoretical framework is articulated in: ",
    "The experimental results are summarized in: ",
    "An in-depth analysis is provided in: ",
    "The abstract for this study states: ",
    "The following citation discusses: ",
    "In their contribution, the authors describe: ",
    "The academic community refers to this work as: ",
    "There is a paper titled ",
    "Citation ",
    "The paper is presented ",
    "The work is documented as follows ",
    "In the literature, the following study is noted ",
    "Reference ",
    "The following research is referenced ",
    "This study is detailed in the paper ",
    "Consider the work titled ",
    "This is articulated in ",
    "The publication can be cited as ",
    "The authors present their findings in ",
    "The research is discussed in ",
    "The following article elaborates on this ",
    "The findings are captured in ",
    "The investigation is reported in ",
    "One example of this is ",
    "In a related publication ",
    "Details of this are found in ",
    "The corresponding paper is titled ",
    "The associated research is documented in ",
    "This idea is explored in ",
    "The topic is studied in ",
    "The article reads ",
    "According to the publication ",
    "An example from the field is ",
    "The authors of this paper highlight ",
    "A detailed exploration is found in ",
    "This research contribution is outlined in ",
    "Their methodology is presented in ",
    "The scientific community recognizes this in ",
    "Insights are shared in ",
    "This innovative approach is explained in ",
    "The theoretical framework is articulated in ",
    "The experimental results are summarized in ",
    "An in-depth analysis is provided in ",
    "The abstract for this study states ",
    "The following citation discusses ",
    "In their contribution, the authors describe ",
    "The academic community refers to this work as ",
    "",
]
